package main

import (
	"log"
	"os"

	"github.com/jmervine/getdown/cli"
	"github.com/jmervine/getdown/server"

	// using text so as not to auto escape html generated by blackfriday
	//"text/template"
)

var cfg = cli.Parse(os.Args)

func main() {
	if cfg.Addr == "" { // will be empty on "help" or "version"
		os.Exit(0)
	}

	svr := server.Bind(cfg)
	log.Printf("at=startup with=%+v\n", *cfg)
	log.Fatal(svr.ListenAndServe())
}
